#===================================================================================================
# Copyright © 2018 nanorep.
# NanorepUI SDK.
# All rights reserved.
#===================================================================================================

platform :ios, "9.0"
use_frameworks!

install! 'cocoapods',
         :deterministic_uuids => false

 BLD_CORE="../../boldcore-mobile-ios/BoldCore-Dev.podspec"
 BLD_AI_ENGINE="../../bold360-mobile-ios-boldaiengine/BoldAIEngine-Dev.podspec"
 BLD_AI_ACCESSIBILITY="../../bold360-mobile-ios-boldaiaccessibility/BoldAIAccessibility-Dev.podspec"
 BLD_ENGINE="../../mobile-bold-engine-ios/BoldEngine-Dev.podspec"
 BLD_360_AI="../../bold360ai-mobile-ios/Bold360AI-Dev.podspec"

#Bold
source 'https://github.com/nanorepsdk/NRSDK-specs.git'

target 'BasicSample' do
    pod 'OpalImagePicker'
    pod 'Bold360AI'
end
