#===================================================================================================
# Copyright © 2018 nanorep.
# NanorepUI SDK.
# All rights reserved.
#===================================================================================================

platform :ios, "9.0"
use_frameworks!

install! 'cocoapods',
         :deterministic_uuids => false

source 'https://github.com/CocoaPods/Specs'

#Bold
source 'https://github.com/nanorepsdk/NRSDK-specs.git'

target 'BasicSample' do
    pod 'OpalImagePicker'
    pod 'Bold360AI'
end
