#===================================================================================================
# Copyright © 2018 nanorep.
# NanorepUI SDK.
# All rights reserved.
#===================================================================================================

platform :ios, "10.0"
use_frameworks!

install! 'cocoapods',
         :deterministic_uuids => false

 BLD_CORE="../../boldcore-mobile-ios/BoldCore-Dev.podspec"
 BLD_AI_ENGINE="../../bold360-mobile-ios-boldaiengine/BoldAIEngine-Dev.podspec"
 BLD_AI_ACCESSIBILITY="../../bold360-mobile-ios-boldaiaccessibility/BoldAIAccessibility-Dev.podspec"
 BLD_ENGINE="../../mobile-bold-engine-ios/BoldEngine-Dev.podspec"
BLD_360_AI="../../bold360ai-mobile-ios/Bold360AI-Dev.podspec"

# Dev
#source 'https://github.com/nanorepsdk/NRSDK-Dev-specs.git'
# Production
source 'https://github.com/nanorepsdk/NRSDK-specs.git'

source 'https://github.com/CocoaPods/Specs'

target 'fileUploadSample' do
    pod 'OpalImagePicker'
    
    if defined? BLD_360_AI
        pod 'OpalImagePicker'
        pod 'BoldCore', :path => BLD_CORE
        pod 'BoldAIEngine', :path => BLD_AI_ENGINE
        pod 'BoldAIAccessibility', :path => BLD_AI_ACCESSIBILITY
        pod 'BoldEngine', :path => BLD_ENGINE
        pod 'Bold360AI', :path => BLD_360_AI
    else
        pod 'Bold360AI'
    end
end
