#===================================================================================================
# Copyright © 2018 nanorep.
# NanorepUI SDK.
# All rights reserved.
#===================================================================================================

platform :ios, "10.0"
use_frameworks!

install! 'cocoapods',
         :deterministic_uuids => false

 BLD_CORE="../../../BitBucket/mobiledx-ios-sdk-core/BoldCore-Dev.podspec"
 BLD_AI_ENGINE="../../../BitBucket/mobiledx-ios-sdk-bot-engine/BoldAIEngine-Dev.podspec"
 BLD_AI_ACCESSIBILITY="../../../BitBucket/mobiledx-ios-sdk-accessibility/BoldAIAccessibility-Dev.podspec"
 BLD_ENGINE="../../../BitBucket/mobiledx-ios-sdk-live-engine/BoldEngine-Dev.podspec"
BLD_360_AI="../../../BitBucket/mobiledx-ios-sdk-ui/Bold360AI-Dev.podspec"

# Dev
source 'https://github.com/nanorepsdk/NRSDK-Dev-specs.git'
# Production
#source 'https://github.com/nanorepsdk/NRSDK-specs.git'

source 'https://github.com/CocoaPods/Specs'

target 'DXSample' do
    pod 'OpalImagePicker'
    
    if defined? BLD_360_AI
        pod 'BoldCore', :path => BLD_CORE
        pod 'BoldAIEngine', :path => BLD_AI_ENGINE
        pod 'BoldAIAccessibility', :path => BLD_AI_ACCESSIBILITY
        pod 'BoldEngine', :path => BLD_ENGINE
        pod 'Bold360AI', :path => BLD_360_AI
    else
        pod 'Bold360AI'
    end
end
