platform :ios, "10.0"
use_frameworks!

install! 'cocoapods',
         :deterministic_uuids => false

source 'https://github.com/CocoaPods/Specs'
source 'https://github.com/nanorepsdk/NRSDK-specs.git'


target 'm1Sample' do
  pod 'Bold360AI'
end
