# rule identifiers to exclude from default rules
disabled_rules:
  - todo
  - notification_center_detachment
  - nsobject_prefer_isequal
  - unused_optional_binding
  - redundant_string_enum_value
  - blanket_disable_command
  - closure_parameter_position
  - multiple_closures_with_trailing_closure
  # should be enabled after refactor
  - one_declaration_per_file

opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - multiline_arguments
  - one_declaration_per_file
  - vertical_parameter_alignment_on_call
  - operator_usage_whitespace
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

cyclomatic_complexity:
  warning: 20
  error: 40

function_body_length:
  warning: 80
  error: 150

force_unwrapping:
  severity: error

line_length:
  warning: 140
  error: 200
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true

file_length:
  warning: 600
  error: 2000

identifier_name:
  excluded:
    - id
    - vc

large_tuple:
  warning: 2
  error: 10

excluded:
  - Pods
