#===================================================================================================
# Copyright © 2018 nanorep.
# NanorepUI SDK.
# All rights reserved.
#===================================================================================================

platform :ios, "11.0"
install! 'cocoapods', :disable_input_output_paths => true
#inhibit_all_warnings!
use_frameworks!

install! 'cocoapods',
         :deterministic_uuids => false

source 'https://github.com/genesys/dx-sdk-specs-dev'
source 'https://github.com/CocoaPods/Specs'


target 'GenesysMessengerSample' do
    pod 'Bold360AI'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
        end
    end
end
